<img src="https://raw.githubusercontent.com/andre-marcos-perez/ebac-course-utils/main/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Módulo** | Python: Variáveis & Tipos de Dados
Caderno de **Exercícios**<br> 
Professor [André Perez](https://www.linkedin.com/in/andremarcosperez/)

---
Respondido as 02:05:12 AM - 03/05/2023

---

# **Tópicos**

<ol type="1">
  <li>Introdução ao Google Colab;</li>
  <li>Variáveis;</li>
  <li>Números;</li>
  <li><i>Strings;</i></li>
  <li>Boleanos.</li>
</ol>

---

# **Exercícios**

## 1\. Google Colab

Crie uma célula de código que escreva o texto "Olá mundo!", utilize o comando `print`.

In [24]:
print('Olá mundo!')

Olá mundo!

Crie uma célua de texto e adicione uma imagem.

Não coloquei nessa demonstração pois estou usando o VSCode e não o Google Colab

---

## 2\. Números

Preencha as células de código para preencher os valores de (A), (B) e (C) na tabela de ticket médio abaixo:

<br>

| Dia   | Valor Total Vendas | Qtd Total Vendas | Ticket Medio |
|-------|--------------------|------------------|--------------|
| 19/01 | (A)                | 3                | 320.52       |
| 20/01 | 834.47             | (B)              | 119.21       |
| 23/01 | 15378.12           | 5                | (C)          |

In [25]:
# (A)
qtd_total = 3
ticket_medio = 320.52
valor_total = qtd_total * ticket_medio
print(valor_total)

961.56

In [26]:
# (B)
ticket_medio = 119.21
valor_total = 834.47
qtd_total = int(valor_total / ticket_medio)
print(qtd_total)

7

In [27]:
# (C)
qtd_total = 5
valor_total = 15378.12
ticket_medio =  valor_total / qtd_total
print(f'{ticket_medio:.2f}')

3075.62

---

## 3\. Strings

Aplique três métodos distintos na *string* abaixo, você pode conferir alguns métodos neste [link](https://www.w3schools.com/python/python_ref_string.asp):

In [28]:
cancao = 'Roda mundo, roda gigante, roda moinho, roda pião.'
cancao = cancao.replace('pião', 'pavão')
cancao = cancao[0:10].upper() + cancao[10:]
moinho = cancao.find('moinho')
print(moinho)
print(cancao)

31
RODA MUNDO, roda gigante, roda moinho, roda pavão.

Extraia da string abaixo o valor da taxa **selic** na variável `selic` e o valor do **ano** na variavel `ano`. Imprima os valores na tela.

In [29]:
noticia = 'Selic vai a 2,75% e supera expectativas; é a primeira alta em 6 anos.'

onde_selic = noticia.find('%')
selic = noticia[onde_selic-4:onde_selic]
print(selic)

onde_anos = noticia.find('anos')
anos = noticia[onde_anos-2:onde_anos]
print(anos)

2,75
6

---

## 4\. Booleanos

Utilize a tabela da verdade para responder: qual o valor da variável x?

In [30]:
a = False
b = True

x = not a & b

x = True

se a(False) não é o que diz, então a é True

    a(True) e b(True) são verdadeiros assim completando o requisito do operador & para ser verdadeiro